addr: :8765
miniflux: http://miniflux:8080
minio:
  endpoint: minio.onlyquant.top
  accessKeyID: 2EugvoLWSgyJDZ
  bucket: journal
  secure: true
  expiry: 160h
route:
  back:
    base: "/api"
  front:
    dir: "dist"
    index: "dist/index.html"
  journal:
    dir: "journal"
    index: "journal/journal.html"
db:
  name: dashboard
  host: postgres
  port: 5432
  username: onlyquant
