addr: :8765
miniflux: http://miniflux:8080
minio:
  endpoint: minio.onlyquant.top
  accessKeyID: dashboardtest
  bucket: journal
  secure: true
  expiry: 160h
route:
  back:
    base: "/api"
  front:
    dir: "client/dist"
    index: "client/dist/index.html"
  journal:
    dir: "client/journal"
    index: "client/journal/journal.html"
db:
  name: dashboard_test
  host: postgres
  port: 5432
  username: onlyquant
oidc:
  tokenEndpoint: "https://auth.onlyquant.top/api/oidc/token"
  userinfoEndpoint: "https://auth.onlyquant.top/api/oidc/userinfo"
  clientId: "Tp6WnNpVj9Sa8gdPZt8bVGq~yjKnjUZkG8J5IJ~aoIj5-Azn~pXUXq5fPXP-8BLQqOVnxq8P"
