// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters received on the OIDC authorization code callback.
 */
export type AuthQuery = { code: string; redirectUri: string };

/**
 * Response body returned after a successful OIDC token exchange.
 */
export type AuthResponse = { token: string };
