// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Public view of a saved URL bookmark (dashboard model).
 */
export type BookmarkView = {
  id: string;
  url: string;
  title: string;
  click: number;
  domain: string;
  payload: JsonValue;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Increments the click counter on the identified bookmark.
 */
export type ClickBookmarkRequest = { id: string };

/**
 * Confirms the click was recorded.
 */
export type ClickBookmarkResponse = Record<symbol, never>;

/**
 * Carries the fields required to create a new bookmark.
 */
export type CreateBookmarkRequest = {
  url: string;
  title: string;
  domain: string;
  payload: JsonValue;
};

/**
 * Returns the created bookmark.
 */
export type CreateBookmarkResponse = { bookmark: BookmarkView };

/**
 * Identifies the bookmark to soft-delete.
 */
export type DeleteBookmarkRequest = { id: string };

/**
 * Returns the deleted bookmark id.
 */
export type DeleteBookmarkResponse = { id: string };

/**
 * Identifies a single bookmark to fetch.
 */
export type GetBookmarkRequest = { id: string };

/**
 * Returns a single bookmark.
 */
export type GetBookmarkResponse = { bookmark: BookmarkView };

/**
 * Requests all bookmarks for the authenticated user.
 */
export type ListBookmarksRequest = Record<symbol, never>;

/**
 * Returns all bookmarks for the authenticated user.
 */
export type ListBookmarksResponse = { bookmarks: Array<BookmarkView> };

/**
 * Carries the replacement payload for a bookmark update.
 */
export type UpdateBookmarkRequest = {
  /**
   * Path parameter — populated from the URL on the backend.
   */
  id: string;
  url: string;
  title: string;
  domain: string;
  payload: JsonValue;
};

/**
 * Returns the updated bookmark.
 */
export type UpdateBookmarkResponse = { bookmark: BookmarkView };
