// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public view of a collection shared across all collection responses.
 */
export type CollectionView = {
  id: string;
  name: string;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Carries the fields required to create a new collection.
 */
export type CreateCollectionRequest = { name: string };

/**
 * Returns the created collection after a successful create request.
 */
export type CreateCollectionResponse = { collection: CollectionView };

/**
 * Identifies which collection to delete.
 */
export type DeleteCollectionRequest = { id: string };

/**
 * Returns the deleted collection id after a successful delete.
 */
export type DeleteCollectionResponse = { id: string };

/**
 * Identifies which collection to fetch.
 */
export type GetCollectionRequest = { id: string };

/**
 * Returns a single collection after a successful fetch.
 */
export type GetCollectionResponse = { collection: CollectionView };

/**
 * Requests all incomplete, non-inbox todos that have a schedule set.
 */
export type ListAllTodosRequest = Record<symbol, never>;

/**
 * Returns all incomplete, non-inbox todos that have a schedule set.
 */
export type ListAllTodosResponse = { todos: Array<TodoView> };

/**
 * Requests the visible collection list for the authenticated user.
 */
export type ListCollectionsRequest = Record<symbol, never>;

/**
 * Returns all visible collections for the authenticated user.
 */
export type ListCollectionsResponse = { collections: Array<CollectionView> };

/**
 * Requests todos scheduled for the current local day.
 */
export type ListTodayTodosRequest = Record<symbol, never>;

/**
 * Returns todos scheduled for today.
 */
export type ListTodayTodosResponse = { todos: Array<TodoView> };

/**
 * Carries the todo IDs to schedule for today.
 */
export type PlanTodayRequest = { ids: Array<string> };

/**
 * Confirms that the plan-today operation completed.
 */
export type PlanTodayResponse = Record<symbol, never>;

/**
 * Public view of a todo item shared across all todo list responses.
 */
export type TodoView = {
  id: string;
  title: string;
  completed: boolean;
  collectionId: string | null;
  difficulty: number | null;
  order: number | null;
  link: string | null;
  draft: string | null;
  schedule: bigint | null;
  done: boolean;
  count: number;
  kanban: string | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Carries the replacement payload for a collection update.
 *
 * The `id` field is the path parameter; it is present in the frontend request type
 * so the generated SDK can build the URL, but the SDK strips it from the JSON body
 * before sending. The backend reads `id` from the URL path instead.
 */
export type UpdateCollectionRequest = {
  /**
   * Path parameter — populated from the URL on the backend; stripped from the JSON body by the SDK.
   */
  id: string;
  name: string;
};

/**
 * Returns the updated collection after a successful update.
 */
export type UpdateCollectionResponse = { collection: CollectionView };
