// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { ClickBookmarkRequest, ClickBookmarkResponse, CreateBookmarkRequest, CreateBookmarkResponse, DeleteBookmarkRequest, DeleteBookmarkResponse, GetBookmarkRequest, GetBookmarkResponse, ListBookmarksRequest, ListBookmarksResponse, UpdateBookmarkRequest, UpdateBookmarkResponse } from "./bookmark.js";
import type { CreateCollectionRequest, CreateCollectionResponse, DeleteCollectionRequest, DeleteCollectionResponse, GetCollectionRequest, GetCollectionResponse, ListAllTodosRequest, ListAllTodosResponse, ListCollectionsRequest, ListCollectionsResponse, ListTodayTodosRequest, ListTodayTodosResponse, PlanTodayRequest, PlanTodayResponse, UpdateCollectionRequest, UpdateCollectionResponse } from "./collection.js";
import type { BookmarkEntryRequest, BookmarkEntryResponse, CreateEntryRequest, CreateEntryResponse, DeleteEntryRequest, DeleteEntryResponse, GetEntryRequest, GetEntryResponse, ListEntriesRequest, ListEntriesResponse, UnbookmarkEntryRequest, UnbookmarkEntryResponse, UpdateEntryRequest, UpdateEntryResponse } from "./entry.js";
import type { DeleteMediaRequest, DeleteMediaResponse } from "./media.js";
import type { CreateTagsRequest, CreateTagsResponse, DeleteTagRequest, DeleteTagResponse, ListTagsRequest, ListTagsResponse } from "./tag.js";
import type { BottomQuickNoteRequest, BottomQuickNoteResponse, CreateQuickNoteRequest, CreateQuickNoteResponse, CreateTiptapRequest, CreateTiptapResponse, DeleteQuickNoteRequest, DeleteQuickNoteResponse, GetTiptapRequest, GetTiptapResponse, ListQuickNotesRequest, ListQuickNotesResponse, ListTiptapHistoryRequest, ListTiptapHistoryResponse, RestoreTiptapHistoryRequest, RestoreTiptapHistoryResponse, UpdateQuickNoteRequest, UpdateQuickNoteResponse, UpdateTiptapRequest, UpdateTiptapResponse } from "./tiptap.js";
import type { GetUserRequest, GetUserResponse, UpdateUserRequest, UpdateUserResponse } from "./user.js";
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  pathParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
  authenticated: boolean;
};

export type RequestByOperation = {
  listCollections: ListCollectionsRequest;
  createCollection: CreateCollectionRequest;
  getCollection: GetCollectionRequest;
  updateCollection: UpdateCollectionRequest;
  deleteCollection: DeleteCollectionRequest;
  listAllTodos: ListAllTodosRequest;
  listTodayTodos: ListTodayTodosRequest;
  planToday: PlanTodayRequest;
  listEntries: ListEntriesRequest;
  createEntry: CreateEntryRequest;
  getEntry: GetEntryRequest;
  updateEntry: UpdateEntryRequest;
  deleteEntry: DeleteEntryRequest;
  bookmarkEntry: BookmarkEntryRequest;
  unbookmarkEntry: UnbookmarkEntryRequest;
  listTags: ListTagsRequest;
  createTags: CreateTagsRequest;
  deleteTag: DeleteTagRequest;
  createTiptap: CreateTiptapRequest;
  getTiptap: GetTiptapRequest;
  updateTiptap: UpdateTiptapRequest;
  listTiptapHistory: ListTiptapHistoryRequest;
  restoreTiptapHistory: RestoreTiptapHistoryRequest;
  listQuickNotes: ListQuickNotesRequest;
  createQuickNote: CreateQuickNoteRequest;
  updateQuickNote: UpdateQuickNoteRequest;
  deleteQuickNote: DeleteQuickNoteRequest;
  bottomQuickNote: BottomQuickNoteRequest;
  listBookmarks: ListBookmarksRequest;
  createBookmark: CreateBookmarkRequest;
  getBookmark: GetBookmarkRequest;
  updateBookmark: UpdateBookmarkRequest;
  deleteBookmark: DeleteBookmarkRequest;
  clickBookmark: ClickBookmarkRequest;
  deleteMedia: DeleteMediaRequest;
  getUser: GetUserRequest;
  updateUser: UpdateUserRequest;
};

export type ResponseByOperation = {
  listCollections: ListCollectionsResponse;
  createCollection: CreateCollectionResponse;
  getCollection: GetCollectionResponse;
  updateCollection: UpdateCollectionResponse;
  deleteCollection: DeleteCollectionResponse;
  listAllTodos: ListAllTodosResponse;
  listTodayTodos: ListTodayTodosResponse;
  planToday: PlanTodayResponse;
  listEntries: ListEntriesResponse;
  createEntry: CreateEntryResponse;
  getEntry: GetEntryResponse;
  updateEntry: UpdateEntryResponse;
  deleteEntry: DeleteEntryResponse;
  bookmarkEntry: BookmarkEntryResponse;
  unbookmarkEntry: UnbookmarkEntryResponse;
  listTags: ListTagsResponse;
  createTags: CreateTagsResponse;
  deleteTag: DeleteTagResponse;
  createTiptap: CreateTiptapResponse;
  getTiptap: GetTiptapResponse;
  updateTiptap: UpdateTiptapResponse;
  listTiptapHistory: ListTiptapHistoryResponse;
  restoreTiptapHistory: RestoreTiptapHistoryResponse;
  listQuickNotes: ListQuickNotesResponse;
  createQuickNote: CreateQuickNoteResponse;
  updateQuickNote: UpdateQuickNoteResponse;
  deleteQuickNote: DeleteQuickNoteResponse;
  bottomQuickNote: BottomQuickNoteResponse;
  listBookmarks: ListBookmarksResponse;
  createBookmark: CreateBookmarkResponse;
  getBookmark: GetBookmarkResponse;
  updateBookmark: UpdateBookmarkResponse;
  deleteBookmark: DeleteBookmarkResponse;
  clickBookmark: ClickBookmarkResponse;
  deleteMedia: DeleteMediaResponse;
  getUser: GetUserResponse;
  updateUser: UpdateUserResponse;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  listCollections: {
    operationName: "listCollections",
    method: "GET",
    pathTemplate: "/api/collections",
    requestType: "ListCollectionsRequest",
    responseType: "ListCollectionsResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  createCollection: {
    operationName: "createCollection",
    method: "POST",
    pathTemplate: "/api/collections",
    requestType: "CreateCollectionRequest",
    responseType: "CreateCollectionResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  getCollection: {
    operationName: "getCollection",
    method: "GET",
    pathTemplate: "/api/collections/{id}",
    requestType: "GetCollectionRequest",
    responseType: "GetCollectionResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  updateCollection: {
    operationName: "updateCollection",
    method: "PUT",
    pathTemplate: "/api/collections/{id}",
    requestType: "UpdateCollectionRequest",
    responseType: "UpdateCollectionResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteCollection: {
    operationName: "deleteCollection",
    method: "DELETE",
    pathTemplate: "/api/collections/{id}",
    requestType: "DeleteCollectionRequest",
    responseType: "DeleteCollectionResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  listAllTodos: {
    operationName: "listAllTodos",
    method: "GET",
    pathTemplate: "/api/todos/all",
    requestType: "ListAllTodosRequest",
    responseType: "ListAllTodosResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  listTodayTodos: {
    operationName: "listTodayTodos",
    method: "GET",
    pathTemplate: "/api/todos/today",
    requestType: "ListTodayTodosRequest",
    responseType: "ListTodayTodosResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  planToday: {
    operationName: "planToday",
    method: "POST",
    pathTemplate: "/api/todos/plan-today",
    requestType: "PlanTodayRequest",
    responseType: "PlanTodayResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  listEntries: {
    operationName: "listEntries",
    method: "GET",
    pathTemplate: "/api/entries",
    requestType: "ListEntriesRequest",
    responseType: "ListEntriesResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  createEntry: {
    operationName: "createEntry",
    method: "POST",
    pathTemplate: "/api/entries",
    requestType: "CreateEntryRequest",
    responseType: "CreateEntryResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  getEntry: {
    operationName: "getEntry",
    method: "GET",
    pathTemplate: "/api/entries/{id}",
    requestType: "GetEntryRequest",
    responseType: "GetEntryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  updateEntry: {
    operationName: "updateEntry",
    method: "PUT",
    pathTemplate: "/api/entries/{id}",
    requestType: "UpdateEntryRequest",
    responseType: "UpdateEntryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteEntry: {
    operationName: "deleteEntry",
    method: "DELETE",
    pathTemplate: "/api/entries/{id}",
    requestType: "DeleteEntryRequest",
    responseType: "DeleteEntryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  bookmarkEntry: {
    operationName: "bookmarkEntry",
    method: "POST",
    pathTemplate: "/api/entries/{id}/bookmark",
    requestType: "BookmarkEntryRequest",
    responseType: "BookmarkEntryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  unbookmarkEntry: {
    operationName: "unbookmarkEntry",
    method: "POST",
    pathTemplate: "/api/entries/{id}/unbookmark",
    requestType: "UnbookmarkEntryRequest",
    responseType: "UnbookmarkEntryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  listTags: {
    operationName: "listTags",
    method: "GET",
    pathTemplate: "/api/tags",
    requestType: "ListTagsRequest",
    responseType: "ListTagsResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  createTags: {
    operationName: "createTags",
    method: "POST",
    pathTemplate: "/api/tags",
    requestType: "CreateTagsRequest",
    responseType: "CreateTagsResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteTag: {
    operationName: "deleteTag",
    method: "DELETE",
    pathTemplate: "/api/tags",
    requestType: "DeleteTagRequest",
    responseType: "DeleteTagResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  createTiptap: {
    operationName: "createTiptap",
    method: "POST",
    pathTemplate: "/api/tiptaps",
    requestType: "CreateTiptapRequest",
    responseType: "CreateTiptapResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  getTiptap: {
    operationName: "getTiptap",
    method: "GET",
    pathTemplate: "/api/tiptaps/{id}",
    requestType: "GetTiptapRequest",
    responseType: "GetTiptapResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  updateTiptap: {
    operationName: "updateTiptap",
    method: "PUT",
    pathTemplate: "/api/tiptaps/{id}",
    requestType: "UpdateTiptapRequest",
    responseType: "UpdateTiptapResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  listTiptapHistory: {
    operationName: "listTiptapHistory",
    method: "GET",
    pathTemplate: "/api/tiptaps/{id}/history",
    requestType: "ListTiptapHistoryRequest",
    responseType: "ListTiptapHistoryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  restoreTiptapHistory: {
    operationName: "restoreTiptapHistory",
    method: "POST",
    pathTemplate: "/api/tiptaps/{id}/history/restore",
    requestType: "RestoreTiptapHistoryRequest",
    responseType: "RestoreTiptapHistoryResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  listQuickNotes: {
    operationName: "listQuickNotes",
    method: "GET",
    pathTemplate: "/api/quicknotes",
    requestType: "ListQuickNotesRequest",
    responseType: "ListQuickNotesResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  createQuickNote: {
    operationName: "createQuickNote",
    method: "POST",
    pathTemplate: "/api/quicknotes",
    requestType: "CreateQuickNoteRequest",
    responseType: "CreateQuickNoteResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  updateQuickNote: {
    operationName: "updateQuickNote",
    method: "PUT",
    pathTemplate: "/api/quicknotes/{id}",
    requestType: "UpdateQuickNoteRequest",
    responseType: "UpdateQuickNoteResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteQuickNote: {
    operationName: "deleteQuickNote",
    method: "DELETE",
    pathTemplate: "/api/quicknotes/{id}",
    requestType: "DeleteQuickNoteRequest",
    responseType: "DeleteQuickNoteResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  bottomQuickNote: {
    operationName: "bottomQuickNote",
    method: "POST",
    pathTemplate: "/api/quicknotes/{id}/bottom",
    requestType: "BottomQuickNoteRequest",
    responseType: "BottomQuickNoteResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  listBookmarks: {
    operationName: "listBookmarks",
    method: "GET",
    pathTemplate: "/api/bookmarks",
    requestType: "ListBookmarksRequest",
    responseType: "ListBookmarksResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  createBookmark: {
    operationName: "createBookmark",
    method: "POST",
    pathTemplate: "/api/bookmarks",
    requestType: "CreateBookmarkRequest",
    responseType: "CreateBookmarkResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  getBookmark: {
    operationName: "getBookmark",
    method: "GET",
    pathTemplate: "/api/bookmarks/{id}",
    requestType: "GetBookmarkRequest",
    responseType: "GetBookmarkResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  updateBookmark: {
    operationName: "updateBookmark",
    method: "PUT",
    pathTemplate: "/api/bookmarks/{id}",
    requestType: "UpdateBookmarkRequest",
    responseType: "UpdateBookmarkResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteBookmark: {
    operationName: "deleteBookmark",
    method: "DELETE",
    pathTemplate: "/api/bookmarks/{id}",
    requestType: "DeleteBookmarkRequest",
    responseType: "DeleteBookmarkResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  clickBookmark: {
    operationName: "clickBookmark",
    method: "POST",
    pathTemplate: "/api/bookmarks/{id}/click",
    requestType: "ClickBookmarkRequest",
    responseType: "ClickBookmarkResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  deleteMedia: {
    operationName: "deleteMedia",
    method: "POST",
    pathTemplate: "/api/media",
    requestType: "DeleteMediaRequest",
    responseType: "DeleteMediaResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  getUser: {
    operationName: "getUser",
    method: "GET",
    pathTemplate: "/api/user",
    requestType: "GetUserRequest",
    responseType: "GetUserResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  updateUser: {
    operationName: "updateUser",
    method: "PUT",
    pathTemplate: "/api/user",
    requestType: "UpdateUserRequest",
    responseType: "UpdateUserResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
} satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
