// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { CreateCollectionRequest, CreateCollectionResponse, DeleteCollectionRequest, DeleteCollectionResponse, GetCollectionRequest, GetCollectionResponse, ListAllTodosRequest, ListAllTodosResponse, ListCollectionsRequest, ListCollectionsResponse, ListTodayTodosRequest, ListTodayTodosResponse, PlanTodayRequest, PlanTodayResponse, UpdateCollectionRequest, UpdateCollectionResponse } from "./collection.js";
import type { DeleteMediaRequest, DeleteMediaResponse } from "./media.js";
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  pathParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
  authenticated: boolean;
};

export type RequestByOperation = {
  listCollections: ListCollectionsRequest;
  createCollection: CreateCollectionRequest;
  getCollection: GetCollectionRequest;
  updateCollection: UpdateCollectionRequest;
  deleteCollection: DeleteCollectionRequest;
  listAllTodos: ListAllTodosRequest;
  listTodayTodos: ListTodayTodosRequest;
  planToday: PlanTodayRequest;
  deleteMedia: DeleteMediaRequest;
};

export type ResponseByOperation = {
  listCollections: ListCollectionsResponse;
  createCollection: CreateCollectionResponse;
  getCollection: GetCollectionResponse;
  updateCollection: UpdateCollectionResponse;
  deleteCollection: DeleteCollectionResponse;
  listAllTodos: ListAllTodosResponse;
  listTodayTodos: ListTodayTodosResponse;
  planToday: PlanTodayResponse;
  deleteMedia: DeleteMediaResponse;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  listCollections: {
    operationName: "listCollections",
    method: "GET",
    pathTemplate: "/api/collections",
    requestType: "ListCollectionsRequest",
    responseType: "ListCollectionsResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  createCollection: {
    operationName: "createCollection",
    method: "POST",
    pathTemplate: "/api/collections",
    requestType: "CreateCollectionRequest",
    responseType: "CreateCollectionResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  getCollection: {
    operationName: "getCollection",
    method: "GET",
    pathTemplate: "/api/collections/{id}",
    requestType: "GetCollectionRequest",
    responseType: "GetCollectionResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  updateCollection: {
    operationName: "updateCollection",
    method: "PUT",
    pathTemplate: "/api/collections/{id}",
    requestType: "UpdateCollectionRequest",
    responseType: "UpdateCollectionResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteCollection: {
    operationName: "deleteCollection",
    method: "DELETE",
    pathTemplate: "/api/collections/{id}",
    requestType: "DeleteCollectionRequest",
    responseType: "DeleteCollectionResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    hasJsonBody: false,
    authenticated: true,
  },
  listAllTodos: {
    operationName: "listAllTodos",
    method: "GET",
    pathTemplate: "/api/todos/all",
    requestType: "ListAllTodosRequest",
    responseType: "ListAllTodosResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  listTodayTodos: {
    operationName: "listTodayTodos",
    method: "GET",
    pathTemplate: "/api/todos/today",
    requestType: "ListTodayTodosRequest",
    responseType: "ListTodayTodosResponse",
    pathParams: [],
    hasJsonBody: false,
    authenticated: true,
  },
  planToday: {
    operationName: "planToday",
    method: "POST",
    pathTemplate: "/api/todos/plan-today",
    requestType: "PlanTodayRequest",
    responseType: "PlanTodayResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
  deleteMedia: {
    operationName: "deleteMedia",
    method: "POST",
    pathTemplate: "/api/media",
    requestType: "DeleteMediaRequest",
    responseType: "DeleteMediaResponse",
    pathParams: [],
    hasJsonBody: true,
    authenticated: true,
  },
} satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
