// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Sets `bookmark = true` on the identified entry.
 */
export type BookmarkEntryRequest = { id: string };

/**
 * Confirms the entry was bookmarked.
 */
export type BookmarkEntryResponse = Record<symbol, never>;

/**
 * Carries the fields required to create a new journal entry.
 */
export type CreateEntryRequest = {
  draft: string | null;
  payload: JsonValue;
  wordCount: number;
  rawText: string;
};

/**
 * Returns the created entry after a successful create.
 */
export type CreateEntryResponse = { entry: EntryView };

/**
 * Identifies the entry to soft-delete.
 */
export type DeleteEntryRequest = { id: string };

/**
 * Returns the deleted entry id.
 */
export type DeleteEntryResponse = { id: string };

/**
 * Public view of a journal entry shared across all entry responses.
 */
export type EntryView = {
  id: string;
  draft: string | null;
  payload: JsonValue;
  wordCount: number;
  rawText: string;
  bookmark: boolean;
  reviewCount: number;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Identifies a single entry to fetch.
 */
export type GetEntryRequest = { id: string };

/**
 * Returns a single entry by id.
 */
export type GetEntryResponse = { entry: EntryView };

/**
 * Query parameters for listing entries with optional filters.
 *
 * All filter fields are optional. When multiple filters are set they are combined with AND.
 * The `random` flag bypasses pagination and returns a randomised sample.
 */
export type ListEntriesRequest = {
  /**
   * 1-indexed page number. Defaults to 1.
   */
  page: number;
  /**
   * Filter entries whose `payload.tags` array contains this tag name.
   */
  tag: string | null;
  /**
   * Case-insensitive full-text search on the `raw_text` field.
   */
  contains: string | null;
  /**
   * When `true`, only return bookmarked entries.
   */
  bookmarked: boolean | null;
  /**
   * When `true`, return a random sample instead of paginated results.
   */
  random: boolean | null;
  /**
   * Return only entries created on this calendar date (YYYY-MM-DD, local time).
   */
  on: string | null;
  /**
   * Return only entries created before this calendar date (YYYY-MM-DD, local time).
   */
  before: string | null;
  /**
   * When `true`, return entries from the same calendar day (month + day) in any year.
   */
  today: boolean | null;
};

/**
 * Returns a page of entries with an indicator of whether more pages exist.
 */
export type ListEntriesResponse = {
  entries: Array<EntryView>;
  hasMore: boolean;
};

/**
 * Sets `bookmark = false` on the identified entry.
 */
export type UnbookmarkEntryRequest = { id: string };

/**
 * Confirms the entry was unbookmarked.
 */
export type UnbookmarkEntryResponse = Record<symbol, never>;

/**
 * Carries the replacement payload for an entry update.
 *
 * The `id` field comes from the URL path on the backend; the generated SDK strips
 * it from the JSON body and interpolates it into the path.
 */
export type UpdateEntryRequest = {
  /**
   * Path parameter — populated from the URL on the backend.
   */
  id: string;
  draft: string | null;
  payload: JsonValue;
  wordCount: number;
  rawText: string;
  bookmark: boolean;
  reviewCount: number;
};

/**
 * Returns the updated entry after a successful update.
 */
export type UpdateEntryResponse = { entry: EntryView };
