// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for the batch media delete endpoint.
 */
export type DeleteMediaRequest = { ids: Array<string> };

/**
 * Response body returned after a successful batch media delete.
 */
export type DeleteMediaResponse = { ids: Array<string> };

/**
 * Response body returned after a successful media upload.
 */
export type UploadResponse = { photos: Array<string> };
