// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests batch creation of tags under a logical group.
 */
export type CreateTagsRequest = { tags: Array<string> };

/**
 * Confirms the batch create completed.
 */
export type CreateTagsResponse = Record<symbol, never>;

/**
 * Identifies the tag to soft-delete by name.
 */
export type DeleteTagRequest = { name: string };

/**
 * Confirms the tag was deleted.
 */
export type DeleteTagResponse = Record<symbol, never>;

/**
 * Requests all tags for the current app context (group resolved from `Only-App` header).
 */
export type ListTagsRequest = Record<symbol, never>;

/**
 * Returns all tag names for the current app context.
 */
export type ListTagsResponse = { tags: Array<TagView> };

/**
 * Public view of a user-defined label.
 */
export type TagView = {
  id: string;
  name: string;
  createdAt: bigint;
  updatedAt: bigint;
};
