// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests batch creation of tags under a logical group.
 */
export type CreateTagsRequest = { tags: Array<string>; group: string };

/**
 * Confirms the batch create completed.
 */
export type CreateTagsResponse = Record<symbol, never>;

/**
 * Identifies the tag to soft-delete by name and group.
 */
export type DeleteTagRequest = { name: string; group: string };

/**
 * Confirms the tag was deleted.
 */
export type DeleteTagResponse = Record<symbol, never>;

/**
 * Requests all tag names for a given group.
 */
export type ListTagsRequest = { group: string };

/**
 * Returns all tag names within the requested group.
 */
export type ListTagsResponse = { tags: Array<TagView> };

/**
 * Public view of a user-defined label.
 */
export type TagView = {
  id: string;
  name: string;
  group: string;
  createdAt: bigint;
  updatedAt: bigint;
};
