// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Moves a quick note to the bottom of the display order.
 */
export type BottomQuickNoteRequest = { id: string };

/**
 * Confirms the quick note was moved to the bottom.
 */
export type BottomQuickNoteResponse = Record<symbol, never>;

/**
 * Carries the fields required to create a new quick note.
 */
export type CreateQuickNoteRequest = { title: string; draft: string | null };

/**
 * Returns the created quick note with its server-assigned display order.
 */
export type CreateQuickNoteResponse = { quickNote: QuickNoteView };

/**
 * Carries the fields required to create a new Tiptap document.
 */
export type CreateTiptapRequest = { site: number; content: JsonValue };

/**
 * Returns the created Tiptap document.
 */
export type CreateTiptapResponse = { tiptap: TiptapView };

/**
 * Identifies the quick note to soft-delete.
 */
export type DeleteQuickNoteRequest = { id: string };

/**
 * Returns the deleted quick note id.
 */
export type DeleteQuickNoteResponse = { id: string };

/**
 * Identifies a single Tiptap document to fetch.
 */
export type GetTiptapRequest = { id: string };

/**
 * Returns a single Tiptap document.
 */
export type GetTiptapResponse = { tiptap: TiptapView };

/**
 * A single snapshot in the tiptap document edit history.
 */
export type HistoryEntryView = { time: bigint; content: JsonValue };

/**
 * Requests all quick notes for the authenticated user.
 */
export type ListQuickNotesRequest = Record<symbol, never>;

/**
 * Returns all quick notes ordered by display order descending.
 */
export type ListQuickNotesResponse = { quickNotes: Array<QuickNoteView> };

/**
 * Requests the edit history timestamps for a Tiptap document.
 */
export type ListTiptapHistoryRequest = { id: string };

/**
 * Returns the list of history entry timestamps in descending order.
 */
export type ListTiptapHistoryResponse = { history: Array<bigint> };

/**
 * Public view of a quick note (dashboard model).
 */
export type QuickNoteView = {
  id: string;
  title: string;
  draft: string | null;
  order: number | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Restores a Tiptap document to a previously saved history snapshot.
 */
export type RestoreTiptapHistoryRequest = {
  /**
   * Path parameter — populated from the URL on the backend.
   */
  id: string;
  /**
   * Timestamp of the history entry to restore.
   */
  ts: bigint;
};

/**
 * Confirms the history snapshot was restored.
 */
export type RestoreTiptapHistoryResponse = Record<symbol, never>;

/**
 * Public view of a Tiptap rich-text document.
 */
export type TiptapView = {
  id: string;
  /**
   * Numeric code identifying the owning surface (entry, quicknote, blog, etc.).
   */
  site: number;
  content: JsonValue;
  history: Array<HistoryEntryView>;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Carries the replacement payload for a quick note update.
 */
export type UpdateQuickNoteRequest = {
  /**
   * Path parameter — populated from the URL on the backend.
   */
  id: string;
  title: string;
  draft: string | null;
  order: number | null;
};

/**
 * Confirms the quick note was updated.
 */
export type UpdateQuickNoteResponse = Record<symbol, never>;

/**
 * Replaces the content of a Tiptap document.
 *
 * The backend atomically backs up the existing content into the `history` array before
 * saving the new content. `ts` is stored as the new `updated_at` millisecond timestamp.
 */
export type UpdateTiptapRequest = {
  /**
   * Path parameter — populated from the URL on the backend.
   */
  id: string;
  content: JsonValue;
  /**
   * New `updated_at` timestamp in milliseconds since epoch.
   */
  ts: bigint;
};

/**
 * Confirms the Tiptap document was updated.
 */
export type UpdateTiptapResponse = Record<symbol, never>;
