// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to fetch the authenticated user's profile.
 *
 * Identity is resolved from the `Onlyquant-Token` header; no body is needed.
 */
export type GetUserRequest = Record<symbol, never>;

/**
 * Response carrying the authenticated user's profile.
 */
export type GetUserResponse = { user: UserView };

/**
 * Request to update the authenticated user's mutable profile fields.
 *
 * All three fields are required; send the current value for fields that should not change.
 */
export type UpdateUserRequest = {
  username: string;
  avatar: string;
  language: string;
};

/**
 * Response carrying the user's profile after the update has been applied.
 */
export type UpdateUserResponse = { user: UserView };

/**
 * Public projection of a user account exposed to frontend consumers.
 *
 * Excludes server-internal fields (id, rss_token, email_token, email_feed).
 * `language` is a raw string on the wire; the frontend layer narrows it to the
 * `UserLang` union type.
 */
export type UserView = {
  username: string;
  email: string;
  avatar: string;
  language: string;
  updatedAt: bigint;
};
