[package]
name = "only-domain"
version.workspace = true
edition.workspace = true

[lib]
name = "only_domain"
path = "src/lib.rs"

[lints]
workspace = true

[features]
sqlx = ["dep:sqlx"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
time = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
